#!/usr/bin/with-contenv bash

# make our folders
mkdir -p \
    /config/www/{backgrounds,icons,avatars,SupportedApps} \
    /app/www \
    /config/log/heimdall

# install heimdall if necessary
[[ -f /heimdall/heimdall.tar.gz ]] && \
 echo "New container detected, installing Heimdall" && \
 tar xf \
     /heimdall/heimdall.tar.gz -C \
    /app/www --strip-components=1 && \
 echo -e '\n# Heimdall user authorization\nfastcgi_param  PHP_AUTH_USER $remote_user;\nfastcgi_param  PHP_AUTH_PW $http_authorization;' >> \
    /etc/nginx/fastcgi_params && \
 rm -rf /heimdall && \
 chown -R abc:abc /app/www

# create symlinks

symlinks=( \
/app/www/storage/app/public/avatars \
/app/www/storage/app/public/backgrounds \
/app/www/storage/app/public/icons \
/app/www/app/SupportedApps \
/app/www/database/app.sqlite \
/app/www/.env )

for i in "${symlinks[@]}"
do
[[ -e "$i" && ! -L "$i" ]] && rm -rf "$i"
[[ ! -L "$i" ]] && ln -s /config/www/"$(basename "$i")" "$i"
done

[[ -e "/app/www/storage/logs/laravel.log" && ! -L "/app/www/storage/logs/laravel.log" ]] \
    && rm -rf "/app/www/storage/logs/laravel.log"
[[ ! -L "/app/www/storage/logs/laravel.log" ]] && \
    ln -s "/config/log/heimdall/laravel.log" "/app/www/storage/logs/laravel.log"

# copy .env if not exists
[[ ! -f /config/www/.env ]] && \
  cp /app/www/.env.example /config/www/.env && \
  echo "Creating app key. This may take a while on slower systems" && \
  php /app/www/artisan key:generate
# set queue driver to database
sed -i 's/QUEUE_DRIVER=sync/QUEUE_DRIVER=database/' /config/www/.env

# permissions
echo "Setting permissions"
chown -R abc:abc \
    /config
